#!/bin/sh

#SBATCH --job-name=nextflow

#SBATCH --ntasks=1
#SBATCH --output=results/nextflow_%j.log
#SBATCH --licenses=sps

####################################

# change to your path 
SCRATCH=/sps/lbmc/lmodolo/nextflow
NXF_TEMP=/sps/lbmc/lmodolo/nextflow/tmp/
mkdir -p ${NXF_TEMP}

${SCRATCH}/nextflow run ${SCRATCH}/src/solution_RNASeq.nf -profile ccin2p3 \
--fastq "${SCRATCH}/data/tiny_dataset/fastq/*_R{1,2}.fastq" \
--fasta "${SCRATCH}/data/tiny_dataset/fasta/tiny_v2.fasta" \
--bed "${SCRATCH}/data/tiny_dataset/annot/tiny.bed" \
-ansi-log \
-w "${SCRATCH}/work/"

wait
